### ISSUE TITLE
Code in AWS serverless app repo is different to github

### ISSUE THREAD

**Issue by aidansteele** [trek10inc/sfn-yaml-macro#1]
Hi,

Great idea for a macro! I tried installing it and didn't have much luck. When I dug in deeper, I discovered that the version of code deployed into my account was looking for the property `DefinitionString` (instead of `Definition`) on the following lines:

https://github.com/trek10inc/sfn-yaml-macro/blob/2355e03920d817c9e39551bfb796c1d751441c78/src/index.py#L32-L35

Was this the case in an earlier version? Maybe the latest code in GitHub hasn't yet been deployed to the SAR?

**Comment by aidansteele** [comment]
If it helps, the version I am using is `0.2.0`

**Comment by mbarneyjr** [comment]
Hi @aidansteele ,

0.1.0 expected `Definition` to be the property used, but we decided to switch to `DefinitionString` since that is the property in the `AWS::StepFunctions::StateMachine` specification, and we wanted to remove the possibility of supplying both `Definition` and `DefinitionString`

The latest version (as of writing) is 0.2.1. If you use the `DefinitionString` property that should work (apologies for the breaking change 😅)

I deployed the latest version in a new account and the template in the example directory worked:
https://github.com/trek10inc/sfn-yaml-macro/tree/master/example

Feel free to re-open if you still have issues!
